
param:
  boundary_kinds: [flow,ec,temp]
  start_date: [2014,1,1] #YYYY,MM,DD
  end_date: [2014,12,31]
file:
  source_map_file: source_map.csv
  schism_flux_file: ./data/flux_v20220222_dated.th
  schism_salt_file: ./data/salt_v20220222_dated.th
  schism_temp_file: ./data/temp_v20220222_dated.th
  out_file_flux: ./output/flux.th.ported
  out_file_salt: ./output/salt.th.ported
  out_file_temp: ./output/temp.th.ported

# list of all relevant CalSim and DSM2 variables (for reference)
calsimvars:
#  - D_RSL004_CCC004 # CCWD Rock
#  - D_OMR021_ORP000 # CCWD OLD
#  - D_VCT002_ORP000 # CCWD Victoria
#  - C_CAA003 # SWP Banks PP 
#  - C_DMC003 # CVP Jones PP
#  - C_AMR004 # American
#  - C_SAC063 # Sacramento d/s of American
#  - C_SJR070 # SJR at Vernalis
#  - C_MOK019 # Mokelumne
#  - C_CLV004 # Calaveras
#  - D_BKR004_NBA009 # Barker Sl PP
#  - C_YBP002 # Yolo Bypass

dsm2vars:
#  - RSAC155
#  - RSAN112
#  - BYOLO040
#  - RCSM075
#  - RMKL070
#  - RCAL009
#  - CHWST000
#  - CHDMC004
#  - SLBAR002
#  - CHCCC006
#  - CHSWP003
#  - CHVCT001
#  - ROLD034